-- select tabname
-- from sysadmin:systables;
-- from sysadmin.systables;

select tabname as TABLE_NAME
from sysadmin:systables
-- from sysadmin.systables
where tabtype='T'
  and tabname not in ('systables'
    , 'syscolumns'
    , 'sysindices'
    , 'systabauth'
    , 'syscolauth'
    , 'sysviews'
    , 'sysusers'
    , 'sysdepend'
    , 'syssynonyms'
    , 'syssyntable'
    , 'sysconstraints'
    , 'sysreferences'
    , 'syschecks'
    , 'sysdefaults'
    , 'syscoldepend'
    , 'sysprocedures'
    , 'sysprocbody'
    , 'sysprocplan'
    , 'sysprocauth'
    , 'sysblobs'
    , 'sysopclstr'
    , 'systriggers'
    , 'systrigbody'
    , 'sysdistrib'
    , 'sysfragments'
    , 'sysobjstate'
    , 'sysviolations'
    , 'sysfragauth'
    , 'sysroleauth'
    , 'sysxtdtypes'
    , 'sysattrtypes'
    , 'sysxtddesc'
    , 'sysinherits'
    , 'syscolattribs'
    , 'syslogmap'
    , 'syscasts'
    , 'sysxtdtypeauth'
    , 'sysroutinelangs'
    , 'syslangauth'
    , 'sysams'
    , 'systabamdata'
    , 'sysopclasses'
    , 'syserrors'
    , 'systraceclasses'
    , 'systracemsgs'
    , 'sysaggregates'
    , 'syssequences'
    , 'sysdirectives'
    , 'sysxasourcetypes'
    , 'sysxadatasources'
    , 'sysseclabelcomponents'
    , 'sysseclabelcomponentelements'
    , 'syssecpolicies'
    , 'syssecpolicycomponents'
    , 'syssecpolicyexemptions'
    , 'sysseclabels'
    , 'sysseclabelnames'
    , 'sysseclabelauth'
    , 'syssurrogateauth'
    , 'sysproccolumns'
    , 'sysexternal'
    , 'sysextdfiles'
    , 'sysextcols'
    , 'sysautolocate'
    , 'sysfragdist'
    , ' GL_COLLATE'
    , ' GL_CTYPE'
    , ' VERSION'
    , 'sysdomains'
    , 'sysindexes'
    , ' SMIVERSION');

select trim(name) as DATABASE from sysmaster:sysdatabases;
